export enum TransferStatus {
  DRAFT = 'DRAFT',
  AWAITING_PAYMENT = 'AWAITING_PAYMENT',
  FUNDED = 'FUNDED',
  CONVERTING = 'CONVERTING',
  ON_CHAIN = 'ON_CHAIN',
  PAYOUT_PENDING = 'PAYOUT_PENDING',
  PAYOUT_SENT = 'PAYOUT_SENT',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  COMPLIANCE_HOLD = 'COMPLIANCE_HOLD',
}
